name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature/system-improvements')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: postgresql://dummy:dummy@localhost:5432/dummy
      VERCEL_BLOB_STORE_ID: dummy
      VERCEL_BLOB_READ_WRITE_TOKEN: dummy
      NEXT_PUBLIC_VERCEL_BLOB_STORE_ID: dummy
      SENTRY_AUTH_TOKEN: dummy
      SENTRY_DSN: dummy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'